/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.temel.pgswingexample.gui;

import com.temel.pgswingexample.Kisi;
import com.temel.pgswingexample.KisiDbIslemleri;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vektorel
 */
public class frmKisiListe extends javax.swing.JFrame {

    KisiDbIslemleri dbIslemleri = new KisiDbIslemleri();

    JPopupMenu popupMenu = new JPopupMenu();
    JMenuItem menuItemAdd = new JMenuItem("Kişi Ekle");

    /**
     * Creates new form frmKisiListe
     */
    public frmKisiListe() {
        initComponents();
        tabloDoldur();
        popupMenuEkle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKisi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblKisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKisi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void tabloDoldur() {
        List<Kisi> kisiList = dbIslemleri.kisileriGetir();
        String[][] data = new String[kisiList.size()][4];

        for (int i = 0; i < kisiList.size(); i++) {
            data[i][0] = kisiList.get(i).getId().toString();
            data[i][1] = kisiList.get(i).getIsim();
            data[i][2] = kisiList.get(i).getSoyisim();
            data[i][3] = kisiList.get(i).getAdres();
        }
        tblKisi.setModel(new DefaultTableModel(data, new String[]{"No", "Ad", "Soyad", "Adres"}));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKisi;
    // End of variables declaration//GEN-END:variables

    private void popupMenuEkle() {
        popupMenu.add(menuItemAdd);
   
        tblKisi.setComponentPopupMenu(popupMenu);
        menuItemAdd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(rootPane, "Selam");
            }
        });
    }
}
